### ISSUE TITLE
Бейджи в боковом баре в разделе Установка и обновление программ

### ISSUE THREAD

**Issue by OlegShchavelev** [OlegShchavelev/ALTKDEWiki#28]
Здорово реализовать бейджи аналогично проект ALT Gnome Wiki, показываю на скриншоте:
![image](https://github.com/OlegShchavelev/ALTKDEWiki/assets/20732384/92765954-ecfe-4c59-9606-3a9fa52de718)

Предлагаю завести следующие бейджи:

- Региональные ограничение
- Проприетарное
- Разработано KDE

**Кому будет интересно как это реализовать:**
- Шаблон бара можно сделать по аналогии с шаблоном [AGWDocsAsideMeta.vue](https://github.com/OlegShchavelev/ALTGnomeWiki/blob/main/.vitepress/theme/components/AGWDocsAsideMeta.vue)
- Конфиг пакета можно взять из аналогичного файла [config.mts](https://github.com/OlegShchavelev/ALTGnomeWiki/blob/main/.vitepress/config.mts)

Также стоит рассмотреть возможность использования нестандартных цветов. Если [стандартных цветов](https://vitepress.dev/ru/reference/default-theme-badge) будет недостаточно, можно создать стили [в специальном файле](https://github.com/OlegShchavelev/ALTGnomeWiki/blob/main/.vitepress/theme/styles/custom.css).

**Comment by Cyber-X-Code** [comment]
Реализовал пункты: Проприетарное и Региональные ограничения. Пункт Разработчик KDE вроде есть, или надо как-то по другому его оформить? И сто касается цветов, можно поподробнее, а то реализую лишнее)

![Снимок экрана от 2024-05-05 21-59-14](https://github.com/OlegShchavelev/ALTKDEWiki/assets/57837842/584871ba-1f0a-4ae8-9c99-2164ee1caf12)
![Снимок экрана от 2024-05-05 22-04-01](https://github.com/OlegShchavelev/ALTKDEWiki/assets/57837842/a2ebb47f-83cc-4d0a-b2d1-5e621cbcc670)

**Comment by trashb1t** [comment]
@Cyber-X-Code Я в своём варианте решил, всё-таки, добавить "Разработано KDE". Так что оставлю пример реализации.
Только цвет более яркий не смог добавить, поэтому синий `type: 'tip'` оставил.
![изображение](https://github.com/OlegShchavelev/ALTKDEWiki/assets/168869588/448ca740-65e2-4a7d-b3e7-0df79d7b9197)

**Comment by Cyber-X-Code** [comment]
Ок, а с КриптоПро CSP, доработать или оставить как есть?

**Comment by trashb1t** [comment]
@Cyber-X-Code Я "Проприетарное" и "Региональные ограничения" оставил, как и у тебя `type: 'danger'`. Но лучше дождаться ответа от автора issue. Может, прояснится что-то.

**Comment by Cyber-X-Code** [comment]
@ trashb1t ну раз сделано, можешь отсылать PR. Я свои правки отменю)))

**Comment by OlegShchavelev** [comment]
> @trashb1t ну раз сделано, можешь отсылать PR. Я свои правки отменю)))

А как я понимаю PR был и ты его отменил @Cyber-X-Code

**Comment by Cyber-X-Code** [comment]
@OlegShchavelev Не успел, решил для начала уточнить что к чему, выяснилось что trashb1t тоже реализовал этот функционал, ну я и не стал делать PR. Щас пытаюсь разобраться с навигацией в KDE при переходе к следующей странице, пока даже не знаю куда смотреть)

**Comment by OlegShchavelev** [comment]
Ой, несколько участников одновременно начали решать одну и ту же проблему. В нашем проекте это случилось впервые.

Возможно, нам стоит ввести дополнительные статусы, чтобы информировать участников о начале работы над задачей.

Приношу извинения за этот инцидент. Давайте подумаем, как организовать трекинг, чтобы участники всегда были в курсе актуальной информации.

**Comment by OlegShchavelev** [comment]
У нас не большая регрессия #38, закрою ISSUE после его исправления.

**Comment by OlegShchavelev** [comment]
Спасибо, большое @trashb1t все работает!
