### ISSUE TITLE
Не работает переход в документацию на локалке

### ISSUE THREAD

**Issue by Krator3** [OlegShchavelev/ALTKDEWiki#54]
Если запустить вики на локалке и попытаться как-либо перейти в документацию, ничего не произойдет. Имеется ввиду, что если нажать на кнопку документации или же найти что-то в поиске, то ссылка в адресной строке обновляется, а сама страница нет. При этом, если открыть какую-нибудь ссылку на документацию в новой вкладке, то там все будет работать. Подобного поведения на вики на сервере не наблюдается.

Ниже приведен пример того, как это выглядит на локалке:
![изображение](https://github.com/OlegShchavelev/ALTKDEWiki/assets/159694894/9326decf-9ef8-4ff1-b354-2bcd647d247e)

А здесь изображено как должно быть (взято с вики на сервере):
![изображение](https://github.com/OlegShchavelev/ALTKDEWiki/assets/159694894/606e040b-6613-495c-a455-c58828409ddc)

**Comment by Ampernic** [comment]
Проверь сейчас работу. По отзыву Олега проблема была исправлена в #55.
